/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/pokemon/{nameOrId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a Pokemon by name or ID */
        get: operations["getPokemon"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Pokemon: {
            id: number;
            name: string;
            /** @description Height in decimeters. */
            height: number;
            /** @description Weight in hectograms. */
            weight: number;
            sprites: {
                /** Format: uri */
                front_default: string | null;
            };
            types: {
                slot: number;
                type: components["schemas"]["NamedResource"];
            }[];
            abilities: {
                ability: components["schemas"]["NamedResource"];
                is_hidden: boolean;
                slot: number;
            }[];
        };
        NamedResource: {
            name: string;
            /** Format: uri */
            url: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getPokemon: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example pikachu */
                nameOrId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A Pokemon resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pokemon"];
                };
            };
            /** @description Pokemon not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
